<?php
/**
 * @file
 */

/**
 * Implements hook_suggestions_profile_info().
 */
function cegeka_suggestion_profiles_suggestions_profile_info() {
  $profiles = array();

  $profiles['production'] = array(
    'title' => t('Cegeka - Production'),
    'description' => t('Suggestions which can be helpful on a production environment.'),
    'suggestions callback' => 'cegeka_suggestion_profiles_production_suggestions',
    'file' => 'production_profile.inc',
    'file path' => drupal_get_path('module', 'cegeka_suggestion_profiles') . '/inc/',
  );

  $profiles['development'] = array(
    'title' => t('Cegeka - Development'),
    'description' => t('Suggestions which can be helpful on a development environment.'),
    'suggestions callback' => 'cegeka_suggestion_profiles_development_suggestions',
    'file' => 'development_profile.inc',
    'file path' => drupal_get_path('module', 'cegeka_suggestion_profiles') . '/inc/',
  );

  $profiles['general'] = array(
    'title' => t('Cegeka - General'),
    'description' => t('General suggestions.'),
    'suggestions callback' => 'cegeka_suggestion_profiles_general_suggestions',
    'file' => 'general_profile.inc',
    'file path' => drupal_get_path('module', 'cegeka_suggestion_profiles') . '/inc/',
  );

  return $profiles;
}
